model_path: /nvme/qa_test_models
resource_path: /nvme/qa_test_models/resource
log_path: /nvme/qa_test_models/autotest_model/log
benchmark_path: /nvme/qa_test_models/benchmark-reports
dataset_path: /nvme/qa_test_models/datasets/ShareGPT_V3_unfiltered_cleaned_split.json
env_tag: 5080

tp_config:
    empty: 2

turbomind_chat_model:
    - meta-llama/Llama-3.2-3B-Instruct
    - meta-llama/Llama-3.2-1B-Instruct
    - OpenGVLab/InternVL3-2B-Instruct
    - OpenGVLab/InternVL3-1B-Instruct
    - OpenGVLab/InternVL2_5-1B
    - Qwen/Qwen3-4B
    - Qwen/Qwen3-1.7B
    - Qwen/Qwen3-0.6B

pytorch_chat_model:
    - meta-llama/Llama-3.2-3B-Instruct
    - meta-llama/Llama-3.2-1B-Instruct
    - OpenGVLab/InternVL3-2B-Instruct
    - OpenGVLab/InternVL3-1B-Instruct
    - OpenGVLab/InternVL2_5-1B
    - Qwen/Qwen3-4B
    - Qwen/Qwen3-1.7B
    - Qwen/Qwen3-0.6B
    - Qwen/Qwen2.5-VL-3B-Instruct

turbomind_vl_model:
    - OpenGVLab/InternVL3-2B-Instruct
    - OpenGVLab/InternVL3-1B-Instruct
    - OpenGVLab/InternVL2_5-1B

pytorch_vl_model:
    - OpenGVLab/InternVL3-2B-Instruct
    - OpenGVLab/InternVL3-1B-Instruct
    - OpenGVLab/InternVL2_5-1B
    - Qwen/Qwen2.5-VL-3B-Instruct

turbomind_base_model:
    - Qwen/Qwen3-4B

pytorch_base_model:
    - Qwen/Qwen3-4B

turbomind_quatization:
    no_awq:
        - OpenGVLab/InternVL3-2B-Instruct
    gptq:
        - empty
    no_kvint4:
        - meta-llama/Llama-3.2-1B-Instruct
        - OpenGVLab/InternVL3-2B-Instruct
        - OpenGVLab/InternVL3-1B-Instruct
        - OpenGVLab/InternVL2_5-1B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-1.7B
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen2.5-VL-3B-Instruct
    no_kvint8:
        - deepseek-ai/DeepSeek-V2-Chat

pytorch_quatization:
    awq:
        - meta-llama/Llama-3.2-3B-Instruct
        - OpenGVLab/InternVL2_5-1B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-1.7B
        - Qwen/Qwen3-0.6B
    w8a8:
        - meta-llama/Llama-3.2-3B-Instruct
    no_kvint4:
        - meta-llama/Llama-3.2-1B-Instruct
        - OpenGVLab/InternVL3-2B-Instruct
        - OpenGVLab/InternVL3-1B-Instruct
        - OpenGVLab/InternVL2_5-1B
        - Qwen/Qwen3-4B
        - Qwen/Qwen3-1.7B
        - Qwen/Qwen3-0.6B
        - Qwen/Qwen2.5-VL-3B-Instruct
    no_kvint8:
        - deepseek-ai/DeepSeek-V2-Lite-Chat
